#!/bin/bash
SERVICE_NAME=$(cat .docker-compose-default-service | tr -d '[:space:]')

if [ -z "$SERVICE_NAME" ]; then
	echo "Configure default service name:"
	echo "echo service-name > .docker-compose-default-service"
	exit
fi

if [ "$1" = "--stop" ]; then
	docker-compose stop
	docker-sync stop
	exit 0
fi

if [ "$1" = "--cleanup" ]; then
	docker-compose stop
	docker-sync stop
	docker-compose rm -f $SERVICE_NAME
	docker-sync clean
	exit 0
fi

# Lets assume the default project name derivated from dir name
COMPOSE_CONTAINER_NAME=$(basename $(pwd) | tr -d '[\-_]')_${SERVICE_NAME}_1

# CHECK DOCKER-SYNC RUNNING
DOCKER_SYNC_PID=$(cat .docker-sync/daemon.pid 2> /dev/null)
if ( [ -z "$DOCKER_SYNC_PID" ] || ! kill -0 $DOCKER_SYNC_PID ); then
	echo "Docker-sync is not running."
	echo "Starting 'docker-sync' in background..."
	DOCKER_SYNC_VERSION=$(docker-sync -v)

	if ! ( echo $DOCKER_SYNC_VERSION | grep '^0\.[2345]' > /dev/null ); then
		echo "ERROR: Docker-sync version $DOCKER_SYNC_VERSION is not supported! Please install docker-sync 0.2.*."
		exit 1
	fi
	docker-sync start
fi

# CHECK DOCKER CONTAINER RUNNNING
CONTAINER_RUNS_TEST=$(docker ps -q -f name=$COMPOSE_CONTAINER_NAME)
if [ -z "$CONTAINER_RUNS_TEST" ]; then
	echo "Container $COMPOSE_CONTAINER_NAME not running... Starting 'docker-compose up' in background"

	# start docker-compose if it is not running
	if [ -f docker-compose.override.yml ]; then
		docker-compose -f docker-compose.yml -f docker-compose.override.yml up -d
	elif [ -f docker-compose.sync.yml ]; then
		docker-compose -f docker-compose.yml -f docker-compose.sync.yml up -d
	else
		echo "WARNING: Starting docker-compose with default docker-compose.yml file"
		docker-compose up -d
	fi
fi

# Run it using docker instead of docker-compose as it is much faster to bootstrap
docker exec -it $COMPOSE_CONTAINER_NAME $@
